---
- name: Install and Configure Shell
  include_tasks: shell.yml

- name: Install and Configure Editor
  include_tasks: editor.yml

- name: Install and Configure Git
  include_tasks: git.yml

- name: Install and Configure JVM Languages
  include_tasks: sdkman.yml
